### ISSUE TITLE
Add file system extraction and render using jsTree

### ISSUE THREAD

**Issue by defrancea** [defrancea/Projbook#48]

**Comment by dasjestyr** [comment]
What would this be? I was just going to add an issue with the following requirements, and I'm not sure if maybe this was a step in that direction:

- On build, the project structure will be mirrored into the documentation project
- For each file in the target project, a docs file will be automatically generated
- For each file in the target project, a file in the docs project will generate the same file, but instead of copying the contents, it will create void method stubs for each public method in the class that it represents. The developer can then fill in the void method with a coded example.
- For each example that is generated, a markdown file template will also be generated so that it will be emitted to the printable document on build.

This will help the developer keep his documents complete while reducing the process involved in creating the template files.

**Comment by defrancea** [comment]
Merge in develop/1.1 from https://github.com/defrancea/Projbook/pull/102
