### ISSUE TITLE
v1.0.6 - Calling MSBuild from the command line fails generating the PDF

### ISSUE THREAD

**Issue by robbihun** [defrancea/Projbook#86]
For example we have build scripts that call msbuild in a build folder (not the same folder as our SLN file)

`msbuild.exe src\solution.sln /t:Clean;Build /p:Configuration=Release;VisualStudioVersion=12.0`

And when running this command I receive the following error on build of the ProjBook project:

`...template.pdf.html : error : Error during PDF generation: Exception has been thrown by the target of an invocation.`

If i remove the Projbook.targets file from the Projbook csproj file then i can build without errors, but that obviously defeats the purpose. I have not dug into the source any more to try and figure out why it might be failing, but i feel like it might be path issue...

**Comment by defrancea** [comment]
Very surprising. Is there any repository from where I can clone a project to repro? I would like to help on that but it's working fine here, at work and from mono. It's possible that it's a path issue but in this case I would like to improve the error message.

**Comment by robbihun** [comment]
Yes, let me see if i can put together a sample that mimics what we're trying to do to see if we get the same error.

**Comment by defrancea** [comment]
Perfect, thanks.

**Comment by robbihun** [comment]
I was able to replicate it with our folder structure -- hopefully a better error message will help us figure this out. https://github.com/robbihun/ProjBookScriptBuildError (running build\run-build.ps1 will replicate the error)

**Comment by defrancea** [comment]
Sounds good, I'm going to have a look at it this week end and will let you know if I find something.

**Comment by defrancea** [comment]
I did try to reproduce but from VS and powershell I got no problem building it:
![projbookworking](https://cloud.githubusercontent.com/assets/456054/14227691/1da94916-f8b8-11e5-8a50-ffec0a1057a6.png)

You'll find a file at src\services\packages\Projbook.1.0.6\build\Projbook.props matching this content: https://github.com/defrancea/Projbook/blob/master/resources/Projbook.props
Could you please replace $(MSBuildProjectFullPath) by the full path of the csproj file of your documentation project and see if it works? I think that the MSBuild version used from your script and from your Visual Studio are different and the MSBuild one doesn't populate any value in this variable.
I can change this props file in order to have fallbacks to cover your case but we need to confirm that it's actually the problem first and find which value we can use instead in your case.

**Comment by robbihun** [comment]
I updated the Projbook.props file and receive the same error.

![image](https://cloud.githubusercontent.com/assets/138997/14251278/ca25a58c-fa47-11e5-8627-8c5392002229.png)

 I also went a step further and updated the .targets file with all of the paths that should be what msbuild generates and get the same error.
![image](https://cloud.githubusercontent.com/assets/138997/14251312/e6a4b61c-fa47-11e5-9b50-675737ca4efe.png)

**Comment by defrancea** [comment]
Amazing, I got a repro. The problem appear when powerhsell runs as admin.
I'm definitely going to address that, thanks a lot for noticing and reporting it.
In the mean time what you ca do is:
* Either disable the pdf generation (removing both keys template-pdf and output-pdf.html from the projbook.json)
* Or run your powershell as user

**Comment by defrancea** [comment]
I was pretty busy with the 1.1 version and the plugin loading so I couldn't have a look at it until now.
Very interesting bug, the actual error is: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

It comes from the underlying wkhtmltopdf dependency executing native dll. When it runs the first time it extracts the file wkhtmltox0.dll being the native one and keeps it for the next executions. In your case, visual studio have been previously executed extracting it for 64 bits. If you run poweshell as user (64) it keeps working, however when you run it as admin by default it runs as 32 bits, the dll is then incompatible and crash.
You can do the test by removing the wkhtmltox0.dll file in packages/Projbook.1.0.6/tools and it will likery work from your admin powershell but will crash switching back to visual studio.
As a fix, I can try to detect that this hapenned, wipe the file and retry during the build, it would make it transparent.

**Comment by defrancea** [comment]
Alright, so I just pushed an error message improvement (see right above). I tried to fix it silently but it will definitely lead to unpredictable behavior relating to file access hold by MSBuild.
Also, because of https://github.com/defrancea/Projbook/issues/70, with 1.1 version you'll likely want to define the architecture you want to have the pdf generated on so it will be consistent across all builds.
For your scenario, I advice you to simply run the script with the same architecture of the one you run your visual studio, it will make them compatible and everything should be alright.
